/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Usuario;

/**
 *
 * @author savio
 */
public class PaginaInicial extends javax.swing.JFrame {
    
    static Usuario logado = new Usuario();
    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial(Usuario usuario) {
        this();
        logado = usuario;  
        labelLogin.setText(logado.getLogin());
    }

    public PaginaInicial(){
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        btIdeiaOnline = new javax.swing.JButton();
        btIdeiaPresencial = new javax.swing.JButton();
        btMostrarTodas = new javax.swing.JButton();
        btMostrarMinhas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Logado como:");

        labelLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btIdeiaOnline.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btIdeiaOnline.setText("Cadastrar Ideia (Online)");
        btIdeiaOnline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btIdeiaOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdeiaOnlineActionPerformed(evt);
            }
        });

        btIdeiaPresencial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btIdeiaPresencial.setText("Cadastrar Ideia (Presencial)");
        btIdeiaPresencial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btIdeiaPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdeiaPresencialActionPerformed(evt);
            }
        });

        btMostrarTodas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMostrarTodas.setText("Mostrar todas Ideias");
        btMostrarTodas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btMostrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTodasActionPerformed(evt);
            }
        });

        btMostrarMinhas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMostrarMinhas.setText("Mostrar minhas Ideias");
        btMostrarMinhas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btMostrarMinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarMinhasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMostrarMinhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMostrarTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIdeiaOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIdeiaPresencial, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addComponent(btIdeiaOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btIdeiaPresencial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMostrarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMostrarMinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIdeiaPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdeiaPresencialActionPerformed
        // TODO add your handling code here:
        CadastrarIdeiaPresencial cadastrarIdeiaPresencial = new CadastrarIdeiaPresencial(logado);
        cadastrarIdeiaPresencial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btIdeiaPresencialActionPerformed

    private void btMostrarMinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarMinhasActionPerformed
        // TODO add your handling code here:
        MostrarMinhasIdeias mostrarMinhasIdeias = new MostrarMinhasIdeias(logado);
        mostrarMinhasIdeias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMostrarMinhasActionPerformed

    private void btIdeiaOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdeiaOnlineActionPerformed
        // TODO add your handling code here:
        CadastrarIdeiaOnline cadastrarIdeiaOnline = new CadastrarIdeiaOnline(logado);
        cadastrarIdeiaOnline.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btIdeiaOnlineActionPerformed

    private void btMostrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTodasActionPerformed
        // TODO add your handling code here:
        MostrarTodasIdeias mostrarTodasIdeias = new MostrarTodasIdeias(logado);
        mostrarTodasIdeias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMostrarTodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIdeiaOnline;
    private javax.swing.JButton btIdeiaPresencial;
    private javax.swing.JButton btMostrarMinhas;
    private javax.swing.JButton btMostrarTodas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    // End of variables declaration//GEN-END:variables
}
